CREATE TABLE `Users Table` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` MEDIUMTEXT NULL DEFAULT NULL,
  `password` MEDIUMTEXT NULL DEFAULT NULL,
  `username` MEDIUMTEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

CREATE TABLE `Reviews Table` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `user_id` INTEGER NOT NULL DEFAULT 0,
  `business_id` INTEGER NOT NULL DEFAULT 0,
  `text` MEDIUMTEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

CREATE TABLE `Business Table` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `name` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `CheckIns` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `user_id` INTEGER NOT NULL DEFAULT NULL,
  `business_id` INTEGER NOT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `currentSearch`;
        
CREATE TABLE `currentSearch` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `name` MEDIUMTEXT NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);